In [8]:
import numpy as np

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
arr1 = np.array([[1, 3, 5, 7], [2, 4, 6, 8]])
arr2 = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(arr)
print(arr1.shape)
print(arr2.shape)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
(2, 4)
(2, 2, 2)


In [ ]:
print(arr.shape)

(12,)


In [ ]:
print(arr1.shape)

(2, 4)


In [ ]:
print(arr2.shape)

(2, 2, 2)


In [ ]:
print(arr.ndim)

1


In [ ]:
print(arr1.ndim)
print(arr2.ndim)

2
3


In [ ]:
print(arr.size)
print(arr1.size)
print(arr2.size)

12
8
8


In [ ]:
arr3=np.arange(0,20,2)
print(arr3)

[ 0  2  4  6  8 10 12 14 16 18]


In [ ]:
arr4=np.random.rand(10)
print(arr4)

[0.67890822 0.87508378 0.2331291  0.22088561 0.58571549 0.70077308
 0.70234595 0.75382919 0.13032384 0.9720902 ]


In [ ]:
arr5=np.random.rand(3,5)
print(arr5)

[[0.17019476 0.71103683 0.73041661 0.11532159 0.31985393]
 [0.27644642 0.64496239 0.18302774 0.15118168 0.38257792]
 [0.51598136 0.81679881 0.63097411 0.48063202 0.51747296]]


In [ ]:
arr6 = np.linspace(10, 20, 5)
print("The array over the given range is ",arr6)

The array over the given range is  [10.  12.5 15.  17.5 20. ]


In [ ]:
array_2d = np.ones((2, 3))
print(array_2d)

[[1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
arr6 = np.zeros(5)
print(arr6)


[0. 0. 0. 0. 0.]


In [ ]:
array7 = np.arange(1, 4)
mainDiagonal = np.diag(array7)
print('Array7:\n',array7)
print('Array7 as main diagonal elements:\n', mainDiagonal)

Array7:
 [1 2 3]
Array7 as main diagonal elements:
 [[1 0 0]
 [0 2 0]
 [0 0 3]]


In [ ]:
arr8=np.random.rand(5,5)
print(arr8)
print(np.sum(arr8,axis=0))
print(np.sum(arr8,axis=1))

[[0.62717653 0.35836613 0.99525378 0.94856667 0.53770806]
 [0.05239889 0.50729374 0.31630719 0.86380969 0.07730929]
 [0.70552758 0.67493238 0.90981536 0.71210976 0.57287841]
 [0.02810293 0.91782033 0.31061639 0.24028714 0.84301273]
 [0.26545114 0.86031285 0.78167783 0.98008963 0.25033446]]
[1.67865707 3.31872544 3.31367055 3.74486289 2.28124295]
[3.46707116 1.81711881 3.5752635  2.33983952 3.13786591]


In [ ]:
array = np.array([[10, 17, 25],
                  [15, 11, 22]])
minValue = np.min(array)
print('The smallest element in the flattened array: ', minValue)
minValue = np.min(array, axis = 0)
print('The smallest element in each column (axis 0): ', minValue)

The smallest element in the flattened array:  10
The smallest element in each column (axis 0):  [10 11 22]


In [ ]:
array = np.array([[10, 17, 25],
                  [15, 11, 22]])
maxValue = np.max(array)
print('The largest element in the flattened array: ', maxValue)
maxValue = np.max(array, axis = 0)
print('The largest element in each column (axis 0): ', maxValue)

The largest element in the flattened array:  25
The largest element in each column (axis 0):  [15 17 25]


In [9]:
arr = [[14, 17, 12, 33, 44],
       [15, 6, 27, 8, 19],
       [23, 2, 54, 1, 4, ]]
print("\nmean of arr, axis = None : ", np.mean(arr))
print("\nmean of arr, axis = 0 : ", np.mean(arr, axis = 0))
print("\nmean of arr, axis = 1 : ", np.mean(arr, axis = 1))


mean of arr, axis = None :  18.6

mean of arr, axis = 0 :  [17.33333333  8.33333333 31.         14.         22.33333333]

mean of arr, axis = 1 :  [24.  15.  16.8]


In [12]:
student_marks = [45, 50, 89, 32, 71, 29, 90, 40, 50, 60, 35, 80, 47]
num_failed = sum(1 for mark in student_marks if mark < 30)
pass_marks = [mark for mark in student_marks if mark >= 30]
num_passed = len(student_marks) - num_failed
print("Number of students who passed: ", num_passed)
print("Number of students who failed: ", num_failed)
print("Marks of students who failed: ", [mark for mark in student_marks if mark < 30])
print("Marks of students who passed: ", pass_marks)

Number of students who passed:  12
Number of students who failed:  1
Marks of students who failed:  [29]
Marks of students who passed:  [45, 50, 89, 32, 71, 90, 40, 50, 60, 35, 80, 47]


In [13]:
m, n = 5, 4
arr = np.random.randint(1, 51, size=(m, n))
print(arr)

[[40 36 29 37]
 [ 7 31 17 17]
 [ 6 10 41 37]
 [24 21 37 47]
 [13 15 49 43]]


In [15]:
arr = np.arange(-30, 11)
arr = arr[arr % 2 != 0]
print(arr)

[-29 -27 -25 -23 -21 -19 -17 -15 -13 -11  -9  -7  -5  -3  -1   1   3   5
   7   9]
